SELECT SYSDATE, TO_CHAR(SYSDATE, 'DY-MON-YYYY HH24:MI:SS')AS "FORMAT 2", TO_CHAR(SYSDATE, 'day-fmMONTH-fmYEAR')
FROM DUAL;

SELECT Hire_Date, TO_CHAR(MONTHS_BETWEEN(SYSDATE,Hire_Date))
FROM EMPLOYEES;


--SALARY DISPLAY TIME--
SELECT upper(Last_Name), Salary, TO_CHAR(Salary, '$99,999')
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

ALTER SESSION SET NLS_CURRENCY = 'Rs.';

SELECT upper(Last_Name), Salary, TO_CHAR(Salary, 'L99,999')
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

-- QUERY TO DSIPLAY HIRE_DATE, SALARY, SALARY+4 MONTHS, FOR ALL WORKING IN DEPT_ID 100, FORMAT DATE TO 'SUNDAY, THE THIRTY-FIRST OF MAY 2003--
SELECT Last_Name, Salary, ADD_MONTHS(Hire_Date,4) AS "Salary of 4 Months", Hire_Date, TO_CHAR(Hire_Date, 'Day,fmDdspth "of" Month YYYY') AS "PRECISE HIRE DATE"
FROM EMPLOYEES
WHERE Department_ID = 100;

--QUERY TO DISPLAY MATOS EARNS $20,600.00 MONTHLY BUT WANTS $78,000.00--

SELECT Last_Name||' earns'||TO_CHAR(SALARY, '$09,999.00')||' monthly but wants'||TO_CHAR(Salary*3,'$09,999.00')AS "Who earns what"
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

SELECT NULLIF('Am','Amey')  
FROM DUAL;


--QUERY TO DSIPLAY DEPT_NAME, NUMBER, MGR_ID, WHO ARE IN LOCATION 1700 IF DEPT HAS MANAGER, PRINT HAS MANAGER
--ELSE NO MANAGER. USE NVL2

SELECT DEPARTMENT_NAME, DEPARTMENT_ID, MANAGER_ID, NVL2(MANAGER_ID, 'Has Manager','No Manager') AS " MANAGER " 
FROM DEPARTMENTS
WHERE LOCATION_ID = 1700;


-- QUERY TO DISPLAY EMP L_NAME, SALARY, COMMISSION_PCT, WORKING IN DPET_ID 110 AND 80. IF EMP DOESN'T EARN COMMISION PRINT NO COMMSION LABEL COLOUMN COMMSION
SELECT Last_Name, Salary, Commision_Pct, NVL(COMMISSION_PCT,'No Commission') AS " COMMISION "
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(110,80);

--QUERY TO DISPLAY EMP LAST_NAME, JOB ID GRADE OF ALL EMPLOYEES BASED ON JOB ID COLUMN 
/* jOB id    Grade
AD_ PRES        A
IT-PROG         B
SA_REP          C
NONE OF THE ABOVE 0 */

SELECT LAST_NAME, JOB_ID, CASE   WHEN JOB_ID = 'AD_PRES' THEN 'A'
                                 WHEN JOB_ID = 'IT_PROG' THEN 'B'
                                 WHEN JOB_ID = 'SA_REP' THEN 'C'
                                ELSE '0'
                         END AS "Garde"
FROM EMPLOYEES;

--USING DECODE--

SELECT LAST_NAME, JOB_ID, DECODE(JOB_ID, 'AD_PRES','A',
                                'IT_PROG','B',
                                'SA_REP','C',
                                '0') AS "Garde"
FROM EMPLOYEES;
