-- QUERY TO DISPLAY LAST_NAME , DEPT_ID FOR EMPLYEE Num 176 --

SELECT Last_Name, Department_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 176;                                             

-- QUERY TO DISPLAY ALL COULMNS OF COUNTRY NAME INDIA
SELECT * FROM COUNTRIES
WHERE COUNTRY_NAME = 'India';

--QUERY TO DISPLAY FULL NAME AND SHOW IT AS FULL NAME, HIRE DATE, DEPT_ID IN 2008 --

SELECT Last_Name|| ' ' ||First_Name AS "Full Name" , Hire_Date, Department_ID
FROM EMPLOYEES
WHERE Hire_Date BETWEEN '01-Jan-2008' AND '31-Dec-2008' 
ORDER BY Department_ID, Hire_date
FETCH FIRST 17 ROWS ONLY;


-- DISPLAY THE LAST NAME, SALARY OF ALL EMPLOYEES WHO HAVE IT_ AS JOB ID AND WHO DO NOT EARN 4200 OR 4800--

SELECT Last_Name, Salary , Job_ID
FROM EMPLOYEES
WHERE Job_ID LIKE 'IT%'
AND SALARY NOT IN (4200,4800);