-- QUERY TO DISPLAY EMP NAME, ID, DEP_NUM, SALARY WHO WORK IN DEPT_ID(10,40,90) AND SORT IT BY DEPT-ID IN DESC, SALARY ASC, EMP_ID DESC

SELECT Last_Name||' '||First_Name AS "Employee Name" , Employee_ID, Department_ID, Salary
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(10,40,90)
ORDER BY 3 DESC, 4 ASC, 2 DESC;

-- QUERY TO DISPLAY DEPT_ID, NAME OF ALL DEPTS IN LOCATION 1700. SORT THEM BY DEPT ID AND LIMIT TO 4 ROWS AND SKIP 1ST 3--
SELECT Department_ID, Department_Name
FROM DEPARTMENTS
WHERE Location_ID IN (1700)
ORDER BY 1
OFFSET 3 ROWS FETCH NEXT 4 ROWS ONLY;

-- QUERY TO DISPLAY AND PROMPT USER TO ENTER DEPT_ID AND THEN EMP_ID, LAST_NAME, SALARY, DEPT_ID, MGR_ID WITH 90 AND 100 AS TEST CASES
SET VERIFY ON
SELECT Employee_ID, Last_Name, Salary, &DeptID, Manager_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = &deptID
ORDER BY &deptID;
