-- QUERY TO DISPLAY LAST NAME OF EMPLOYEE IN CAPS , DEPT NUM, WHOSE NAMES START WITH 'A' GIVE PROPER NAME FOR COLUMN AND SORT BY EMP LAST_NAME

SELECT UPPER(Last_Name) AS "Last Name", Department_ID
FROM EMPLOYEES
WHERE Last_Name LIKE '&Alphabet%' 
ORDER BY Last_Name;

SELECT FIRST_NAME, LAST_NAME, CONCAT( CONCAT(FIRST_NAME, ' '),LAST_NAME) AS "Name"
FROM EMPLOYEES
FETCH FIRST 17 ROWS ONLY;

-- QUERY TO DEPT_NUM , NAME, LENGTH OF DEPT_NAME , DISPLAY LAST 4 CHACTERS OF DEPT_NAME FOR ALL LOCATED IN 1700 

SELECT Department_ID, Department_Name, LENGTH(Department_Name)AS "Length of Dept Name", SUBSTR(Department_Name, -4,4) AS "Last 4 char of Dept Name"
FROM DEPARTMENTS
WHERE Location_ID = 1700
ORDER BY LENGTH(Department_Name) DESC
FETCH FIRST 17 ROWS ONLY;

-- QUERY TO DISPLAY COUNTRY NAME, ID , REPLACE ALL COUNTRY NAMES WITH ** AS 1ST TWO CHARACTERS
SELECT Country_ID, Country_Name, REPLACE (Country_Name, SUBSTR(COUNTRY_NAME, 1,2) ,'**') AS "New Name"
FROM COUNTRIES;

-- QUERY TO DISPLAY EMP_NUM, L_NAME, SALARY, SALARY*10% ROUND OFF TO 0 DECIMAL PTS WHO WORK IN DEPT NUM 100 

SELECT Employee_ID, Last_Name, Salary, ROUND(Salary+(Salary*0.1),0) AS "New Salary"
FROM EMPLOYEES
WHERE Department_ID = 100
ORDER BY &Column ;

SELECT MOD(30,7), CEIL(79.3), FLOOR(34.7)
FROM DUAL;

SELECT SYSDATE,ADD_MONTHS(SYSDATE, 100), NEXT_DAY(SYSDATE,'Sunday'), LAST_DAY(SYSDATE), MONTHS_BETWEEN(SYSDATE,'21-Apr-21')
FROM DUAL;

SELECT SYSDATE, EXTRACT(DAY FROM SYSDATE)
FROM DUAL;

SELECT SYSDATE AS "Today's Date", SYSDATE-1 AS "Yesterday's Date", SYSDATE+1 AS "Tomorrow's Date"
FROM DUAL;

SELECT Last_Name, Hire_Date, ADD_MONTHS(Hire_Date,3)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30;
