SELECT * FROM COUNTRIES;
-- SQL GROUP FUNCTION--
ALTER SESSION SET NLS_CURRENCY = 'Rs.';

SELECT MAX(SALARY),MIN(SALARY),COUNT(*),ROUND(AVG(SALARY),2), SUM(SALARY)
FROM EMPLOYEES;

SELECT COUNT(NVL(COMMISSION_PCT,0))AS " NO COMMISSION"
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL 

SELECT UNIQUE(first_name)
FROM
    employees;
    
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS


SELECT DISTINCT (Salary)
FROM EMPLOYEES
ORDER BY Salary DESC
WHERE ROWNUM=2;
DESCRIBE EMPLOYEES;

-- QUERY TO DISPLAY NO.OF EMPLOYEES WORKING IN THE SAME DEPT AND SORTING THEM BY NO,OF WORKERS IN DESC --
SELECT JOB_ID, COUNT(Employee_ID) AS "NO.OF WORKERS"
FROM EMPLOYEES
GROUP BY JOB_ID
ORDER BY COUNT(Employee_ID) DESC;

-- QUERY TO DISPLAY NO.OF DEPTS IN EACH LOCATION --
SELECT LOCATION_ID, COUNT(DEPARTMENT_ID) AS "No.of Depts"
FROM DEPARTMENTS
GROUP BY LOCATION_ID;
 
 -- QUERY TO DISPLAY AVG,MIN,MAX,SUM SLARY OF ALL DEPTS AND JOBS
 
 SELECT DEPARTMENT_ID,JOB_ID,SUM(SALARY),ROUND(AVG(SALARY),2),MIN(SALARY),MAX(SALARY)
 FROM EMPLOYEES
 GROUP BY JOB_ID, DEPARTMENT_ID
 ORDER BY 1;
 
-- QUERY TO DISPLAY THE REDGION ID'S THAT HAVE MORE THAN 5 COUNTRIES --
SELECT REGION_ID, COUNT(COUNTRY_ID)AS "No.of Countries"
FROM COUNTRIES
GROUP BY REGION_ID
HAVING COUNT(*)>5
ORDER BY 2;

SELECT JOB_ID, DEPARTMENT_ID, SUM(SALARY) AS "SUM OF SALARY"
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (50,80)
GROUP BY JOB_ID,DEPARTMENT_ID
HAVING  SUM(SALARY)>60000;

SELECT ROUND(AVG(SALARY),1)
FROM EMPLOYEES;

